updated on Sun Nov 25 20:22:22 UTC 2012

diff --git a/alx-driver.install b/alx-driver.install
--- a/alx-driver.install
+++ b/alx-driver.install
@@ -1,33 +1,44 @@
-generic() {
-    echo " > Running depmod now..."
-    depmod -a
-}
+DKMS=`which dkms`
+DEPMOD=`which depmod`
+MODPROBE=`which modprobe`
+RMMOD=`which rmmod`
+MNAME="alx"
+MVER="20121003"
 
-unload() {
-    lsmod | grep alx > /dev/null
-    if [ "$?" = "0" ]; then
-        rmmod alx
+post_install() {
+    echo "Running dkms for install..."
+    ${DKMS} add -m ${MNAME} -v ${MVER} &&\
+    ${DKMS} build -m ${MNAME} -v ${MVER} &&\
+    ${DKMS} install -m ${MNAME} -v ${MVER}
+
+    if [ "$?" == "0" ]; then
+        ${RMMOD} ${MNAME}
+        ${MODPROBE} ${MNAME}
+        ${DEPMOD} -a
+    else
+        echo "An error was ocurred, please report the bug!."
+        return 2
     fi
 }
 
-post_install() {
-    generic
-    echo " > Reloading alx module..."
-    echo "   Please note that you may REBOOT your system to get it works!"
-    unload
-    sleep 0.5
-    modprobe alx
+pre_remove() {
+    #Sadly stolen(and modified) from dkms-alx package
+
+    echo "Running dkms for remove/upgrade..."
+    line=`$DKMS status -m ${MNAME}`
+    if echo "$line" | grep -E 'added|built|installed'; then
+            version=`echo "$line" | sed "s/${MNAME},\([^,]*\)[,:].*/\1/;t;d"`
+            ${DKMS} remove -m ${MNAME} -v ${MVER} --all
+    fi
+
+    ${RMMOD} ${MNAME}
+    ${DEPMOD} -a
+}
+
+pre_upgrade() {
+    pre_remove
 }
 
 post_upgrade() {
     post_install
 }
-
-post_remove() {
-    generic
-    echo " > Unloading memory resident module..."
-    unload
-    rmmod compat
-    echo "  Module unloaded!."
-}
-
